/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.example.toml --include-runtime=false --env-interface=CloudflareBindings` (hash: edd5abda637c4cb0d066ee0b9d5a53e4)
interface __BaseEnv_CloudflareBindings {
	GITME_KV: KVNamespace;
	GITME_R2: R2Bucket;
	GITME_AUTH: DurableObjectNamespace<import("./src/worker").AuthUser>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "AuthUser";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
