name = "git-me"
main = "src/worker.js"
compatibility_date = "2026-07-07"
workers_dev = true

[[r2_buckets]]
binding = "GITME_R2"
bucket_name = "git-me-objects"

[[kv_namespaces]]
binding = "GITME_KV"
id = "<kv_namespace_id>"

[build]
command = "make build"
